### ISSUE TITLE
With enabled proxy I got an NPE

### ISSUE THREAD

**Issue by ahoehma** [ingenieux/beanstalker#121]
I'm working behind a company proxy and if the proxy is enabled for maven then
"mvn beanstalk:check-availability" throws an NPE:

[INFO] --- beanstalk-maven-plugin:1.5.4-SNAPSHOT:check-availability (default-cli) @ ipc-service-rest ---
[WARNING] FAILURE
java.lang.RuntimeException: org.apache.maven.plugin.MojoExecutionException: Unable to create service
        at br.com.ingenieux.mojo.aws.AbstractAWSMojo.getService(AbstractAWSMojo.java:386)
        at br.com.ingenieux.mojo.beanstalk.AbstractBeanstalkMojo.getService(AbstractBeanstalkMojo.java:274)
        at br.com.ingenieux.mojo.beanstalk.dns.CheckAvailabilityMojo.executeInternal(CheckAvailabilityMojo.java:49)
        at br.com.ingenieux.mojo.aws.AbstractAWSMojo.execute(AbstractAWSMojo.java:401)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to create service
        at br.com.ingenieux.mojo.aws.AbstractAWSMojo.createServiceFor(AbstractAWSMojo.java:346)
        at br.com.ingenieux.mojo.aws.AbstractAWSMojo.setupService(AbstractAWSMojo.java:337)
        at br.com.ingenieux.mojo.aws.AbstractAWSMojo.getService(AbstractAWSMojo.java:384)
        ... 25 more
Caused by: java.lang.NullPointerException
        at br.com.ingenieux.mojo.aws.AbstractAWSMojo.getDecryptedAwsKey(AbstractAWSMojo.java:250)
        at br.com.ingenieux.mojo.aws.AbstractAWSMojo.getClientConfiguration(AbstractAWSMojo.java:301)
        at br.com.ingenieux.mojo.aws.AbstractAWSMojo.createServiceFor(AbstractAWSMojo.java:342)
        ... 27 more

<servers>
    <server>
      <id>aws.amazon.com</id>
      <username>xxxxx</username>
      <password>xxxx</password>
    </server>
  </servers>
  <proxies>
    <proxy><id>siemens</id><active>true</active><protocol>http</protocol><host>xxxxxxxxx</host><port>xxxxx</port></proxy>
  </proxies>

**Comment by ahoehma** [comment]
I'm able to run the plugin if I provide empty tags for the proxy (our company proxy doesn't need a login):

```
<username></username>
<password></password>
```
