### ISSUE TITLE
Updating worker environment does not work in 1.3.4 and greater

### ISSUE THREAD

**Issue by dlvenable** [ingenieux/beanstalker#58]
I have a worker environment which I cannot update with versions 1.3.4, 1.3.5, and 1.4.0. The specific issue is that the plugin fails to find the environment. The environment is present and the status is Green.

I tried in version 1.3.3 and I am able to update.

**Comment by aldrinleal** [comment]
oops. can you send me in private your pom so I could look into it?

Sent from my Windows Phone

-----Original Message-----

**Comment by dlvenable** [comment]
Our POM is fairly complicated because it uses a parent-child hierarchy. I'll see if I can break down the properties for you.

One important thing to note - running the beanstalk:wait-for-environment Maven goal succeeds just fine in version 1.3.5. There must be something different in how the two wait commands are setup.

**Comment by aldrinleal** [comment]
mvn help:effective-pom

--
-- Aldrin Leal, <aldrin@leal.eng.br>
Master your EC2-fu! Get the latest ekaterminal public beta
http://www.ingenieux.com.br/products/ekaterminal/

**Comment by dlvenable** [comment]
Hello @aldrinleal, I sent you an email at the email address listed in your Git commits for this project.

**Comment by mkalinin** [comment]
hello @aldrinleal, I have the same issue and not sure if I put a proper configuration in POM. Could you, please, refer to working example or some docs describing configuration for the Worker tier.

thanks in advance!

**Comment by scatat** [comment]
mkalinin has also submitted a PR: https://github.com/ingenieux/beanstalker/pull/68 which should address this issue. Is there any chance of it being merged in the next few days/weeks?

**Comment by aldrinleal** [comment]
@dlvenable, can you see if the current snapshot (with the @mkalinin patch) appears to solve your problem?

@scatat, please way, things are a bit slower here :)

**Comment by aldrinleal** [comment]
@mkalinin, there was an archetype example in the service webapp, but I think you saw it.

@dlvenable, I created an example at github.com/aldrinleal/example-awseb-worker.

First, I deployed it with ```mvn -Pawseb deploy```

It had an issue, which was good. Fixed it, then ran the same command again but with wait-for-environment:

```
$ mvn -Pawseb clean deploy beanstalk:wait-for-environment
...
[INFO] Artifact Uploaded
[INFO] SUCCESS
[INFO] null
[INFO]
[INFO] --- beanstalk-maven-plugin:1.4.1-SNAPSHOT:create-application-version (deploy) @ example-worker-app ---
[INFO] SUCCESS
[INFO] {
[INFO]   "applicationName" : "example-worker-app",
[INFO]   "description" : "Update from beanstalk-maven-plugin",
[INFO]   "versionLabel" : "20150918015711",
[INFO]   "sourceBundle" : {
[INFO]     "s3Bucket" : "elasticbeanstalk-us-east-1-235368163414",
[INFO]     "s3Key" : "apps/example-worker-app/example-worker-app-20150918015711.zip"
[INFO]   },
[INFO]   "dateCreated" : 1442541562432,
[INFO]   "dateUpdated" : 1442541562432
[INFO] }
[INFO]
[INFO] --- beanstalk-maven-plugin:1.4.1-SNAPSHOT:put-environment (deploy) @ example-worker-app ---
[INFO] ... with environmentName matching re '\Qexample-worker-app\E'
[INFO] ... with status *NOT* set to 'Terminated'
[INFO] Calling update-environment, and using versionLabel: 20150918015711
[INFO] SUCCESS
[INFO] {
[INFO]   "environmentName" : "example-worker-app",
[INFO]   "environmentId" : "e-9ssmpvubdf",
[INFO]   "applicationName" : "example-worker-app",
[INFO]   "versionLabel" : "20150918015711",
[INFO]   "solutionStackName" : "64bit Amazon Linux 2015.03 v2.0.0 running Docker 1.6.2",
[INFO]   "description" : "example-worker-app",
[INFO]   "dateCreated" : 1442539729398,
[INFO]   "dateUpdated" : 1442541563466,
[INFO]   "status" : "Updating",
[INFO]   "health" : "Grey",
[INFO]   "tier" : {
[INFO]     "name" : "Worker",
[INFO]     "type" : "SQS/HTTP",
[INFO]     "version" : "1.0"
[INFO]   }
[INFO] }
[INFO]
[INFO] --- beanstalk-maven-plugin:1.4.1-SNAPSHOT:wait-for-environment (default-cli) @ example-worker-app ---
[INFO] Environment Lookup
[INFO] ... with environmentName matching re '\Qexample-worker-app\E'
[INFO] ... with status   set to 'Ready'
[INFO] ... with health equal to 'Green'
[INFO] SUCCESS
[INFO] {
[INFO]   "environmentName" : "example-worker-app",
[INFO]   "environmentId" : "e-9ssmpvubdf",
[INFO]   "applicationName" : "example-worker-app",
[INFO]   "versionLabel" : "20150918015711",
[INFO]   "solutionStackName" : "64bit Amazon Linux 2015.03 v2.0.0 running Docker 1.6.2",
[INFO]   "description" : "example-worker-app",
[INFO]   "dateCreated" : 1442539729398,
[INFO]   "dateUpdated" : 1442541701508,
[INFO]   "status" : "Ready",
[INFO]   "health" : "Green",
[INFO]   "tier" : {
[INFO]     "name" : "Worker",
[INFO]     "type" : "SQS/HTTP",
[INFO]     "version" : "1.0"
[INFO]   }
[INFO] }
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:49 min
[INFO] Finished at: 2015-09-17T23:02:00-03:00
[INFO] Final Memory: 33M/126M
[INFO] ------------------------------------------------------------------------
```

...and it worked. I suggest you start by reviewing beanstalk.environmentRef values and paste the lookup prefix (the lines like the ones below) so we can validate it together:

```
[INFO] Environment Lookup
[INFO] ... with environmentId equal to 'e-9ssmpvubdf'
[INFO] ... with status   set to 'Ready'
[INFO] ... with health equal to 'Green'
```

Thank you

**Comment by dlvenable** [comment]
@aldrinleal, it appears that the latest source code does not find the existing environment. The environment does exist and is in the Green state.

```
[INFO] ... with environmentName matching re '\Qweb-worker-TEST\E'
[INFO] ... with status *NOT* set to 'Terminated'
[INFO] Environment Lookup
[INFO] ... with environmentName matching re '\Qweb-worker-TEST\E'
[INFO] ... with status *NOT* set to 'Updating'
[WARNING] FAILURE
org.apache.maven.plugin.MojoExecutionException: Timed out
	at br.com.ingenieux.mojo.beanstalk.cmd.env.waitfor.WaitForEnvironmentCommand.executeInternal(WaitForEnvironmentCommand.java:271)
	at br.com.ingenieux.mojo.beanstalk.cmd.env.waitfor.WaitForEnvironmentCommand.executeInternal(WaitForEnvironmentCommand.java:46)
	at br.com.ingenieux.mojo.beanstalk.cmd.BaseCommand.execute(BaseCommand.java:73)
	at br.com.ingenieux.mojo.beanstalk.AbstractNeedsEnvironmentMojo.waitForNotUpdating(AbstractNeedsEnvironmentMojo.java:490)
	at br.com.ingenieux.mojo.beanstalk.env.UpdateEnvironmentMojo.executeInternal(UpdateEnvironmentMojo.java:211)
	at br.com.ingenieux.mojo.aws.AbstractAWSMojo.execute(AbstractAWSMojo.java:386)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by aldrinleal** [comment]
$ mvn beanstalk:describe-environments. Can you paste its output?

**Comment by dlvenable** [comment]
```
[INFO] --- beanstalk-maven-plugin:1.4.1-SNAPSHOT:describe-environments (default-cli) @ web-worker ---
[INFO] SUCCESS
[INFO] {
[INFO]   "environments" : [ {
[INFO]     "environmentName" : "web-worker-TEST",
[INFO]     "environmentId" : "e-spqiyyjjey",
[INFO]     "applicationName" : "testing-web-worker",
[INFO]     "versionLabel" : "Web Worker 1.0.11",
[INFO]     "solutionStackName" : "64bit Amazon Linux 2014.09 v1.2.0 running Tomcat 7 Java 7",
[INFO]     "description" : "Web Worker",
[INFO]     "dateCreated" : 1443620644771,
[INFO]     "dateUpdated" : 1443623797400,
[INFO]     "status" : "Ready",
[INFO]     "abortableOperationInProgress" : false,
[INFO]     "health" : "Red",
[INFO]     "tier" : {
[INFO]       "name" : "Worker",
[INFO]       "type" : "SQS/HTTP",
[INFO]       "version" : "1.0"
[INFO]     }
[INFO]     }
[INFO]   } ]
[INFO] }
```

The health is Red now because I made some changes. But, it was Green when I ran the first update-environment command.

**Comment by dlvenable** [comment]
I just re-tried update-environment, while the state was Red and it worked.

```
[INFO] ... with environmentName matching re '\Qweb-worker-TEST\E'
[INFO] ... with status *NOT* set to 'Terminated'
[INFO] Environment Lookup
[INFO] ... with environmentName matching re '\Qweb-worker-TEST\E'
[INFO] ... with status *NOT* set to 'Updating'
[INFO] Calling update-environment, and using versionLabel: this Web Worker 1.0.13
[INFO] SUCCESS
[INFO] {
[INFO]   "environmentName" : "web-worker-TEST",
[INFO]   "environmentId" : "e-spqiyyjjey",
[INFO]   "applicationName" : "testing-web-worker",
[INFO]   "versionLabel" : "Web Worker 1.0.13",
[INFO]   "solutionStackName" : "64bit Amazon Linux 2014.09 v1.2.0 running Tomcat 7 Java 7",
[INFO]   "description" : "Web Worker",
[INFO]   "dateCreated" : 1443620644771,
[INFO]   "dateUpdated" : 1443629580842,
[INFO]   "status" : "Updating",
[INFO]   "abortableOperationInProgress" : true,
[INFO]   "health" : "Grey",
[INFO]   "tier" : {
[INFO]     "name" : "Worker",
[INFO]     "type" : "SQS/HTTP",
[INFO]     "version" : "1.0"
[INFO]   }
[INFO] }
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by bpappin** [comment]
this is closed, but doesn't indicate the solution.

**Comment by aldrinleal** [comment]
@bpappin, can you show your maven output and beanstalk.* settings please?

Thank you
