### ISSUE TITLE
MissingFormatArgumentException during beanstalk-maven-plugin:1.4.0:wait-for-environment

### ISSUE THREAD

**Issue by MusikPolice** [ingenieux/beanstalker#84]
When deploying my application to Elastic Beanstalk, I got the following exception that caused the build to fail:
```
[INFO] --- beanstalk-maven-plugin:1.4.0:wait-for-environment (default) @ my-project ---
[INFO] Environment Lookup
[INFO] ... with cname set to 'my-project-dev.elasticbeanstalk.com'
[INFO] ... with status   set to 'Ready'
[INFO] ... with health equal to 'Green'
[INFO] WARN Wed Jan 06 13:29:28 EST 2016 Process termination taking longer than 10 seconds.
[INFO] INFO Wed Jan 06 13:29:35 EST 2016 New application version was deployed to running EC2 instances.
[INFO] INFO Wed Jan 06 13:29:35 EST 2016 Environment update completed successfully.
[WARNING] FAILURE
org.apache.maven.plugin.MojoFailureException: Failed
	at br.com.ingenieux.mojo.aws.AbstractAWSMojo.handleException(AbstractAWSMojo.java:394)
	at br.com.ingenieux.mojo.beanstalk.cmd.BaseCommand.handleException(BaseCommand.java:83)
	at br.com.ingenieux.mojo.beanstalk.cmd.BaseCommand.execute(BaseCommand.java:75)
	at br.com.ingenieux.mojo.beanstalk.env.WaitForEnvironmentMojo.executeInternal(WaitForEnvironmentMojo.java:77)
	at br.com.ingenieux.mojo.aws.AbstractAWSMojo.execute(AbstractAWSMojo.java:357)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.util.MissingFormatArgumentException: Format specifier '% o'
	at java.util.Formatter.format(Formatter.java:2519)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2928)
	at br.com.ingenieux.mojo.beanstalk.cmd.BaseCommand.info(BaseCommand.java:67)
	at br.com.ingenieux.mojo.beanstalk.cmd.env.waitfor.WaitForEnvironmentCommand.executeInternal(WaitForEnvironmentCommand.java:255)
	at br.com.ingenieux.mojo.beanstalk.cmd.env.waitfor.WaitForEnvironmentCommand.executeInternal(WaitForEnvironmentCommand.java:46)
	at br.com.ingenieux.mojo.beanstalk.cmd.BaseCommand.execute(BaseCommand.java:73)
	... 23 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:20.389s
[INFO] Finished at: Wed Jan 06 13:30:15 EST 2016
[INFO] Final Memory: 44M/393M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal br.com.ingenieux:beanstalk-maven-plugin:1.4.0:wait-for-environment (default) on project my-project: Failed: Format specifier '% o' -> [Help 1]
```
This has never happened before, and the next build succeeded as expected. I'm not sure if there's anything that you can do about this, but I figured I'd report it in case it reveals some problem that you weren't previously aware of.

**Comment by aldrinleal** [comment]
Ok, fixed. That was a fast one :)
